FROM nginx

# RUN rm -rf /tmp/* && apt-get update && \
#    apt-get -y install git python python-dev python-pip libsasl2-dev libldap2-dev libssl-dev&& \
#    git clone https://github.com/nginxinc/nginx-ldap-auth.git && \
#    pip install python-ldap && \
#    cd nginx-ldap-auth && \
#    bash nginx-ldap-auth-daemon-ctl.sh start && \
#    python /tmp/nginx-ldap-auth/backend-sample-app.py

{% if nginx_local_testing is defined and nginx_local_testing == 'true' %}
ENV AWS_SESSION_TOKEN {{ nginx_ldap_aws_session_token }}
ENV AWS_SECRET_ACCESS_KEY {{ nginx_ldap_aws_secret_access_key }}
ENV AWS_ACCESS_KEY_ID {{ nginx_ldap_aws_access_key_id }}
{% endif %}

{% for destination in nginx_ldap_app_file_mappings.keys()  %}
ADD {{ nginx_ldap_app_file_mappings[destination]  }} {{ destination }}
{% endfor %}

RUN rm -rf /tmp/* && \
    apt-get update && \
    apt-get -y install {% for req in nginx_ldap_host_requirements %}{{ req }} {% endfor %} && \
    pip install -r requirements.pip && \
    chmod u+x /usr/local/sbin/nginx-auth-backend && \
    chmod u+x /usr/local/sbin/nginx-ldap-daemon

ADD nginx.conf /etc/nginx/nginx.conf
ADD supervisord.conf /etc/supervisor/conf.d/supervisord.conf
ADD cwl.conf /etc/cwl.conf
RUN curl https://s3.amazonaws.com/aws-cloudwatch/downloads/latest/awslogs-agent-setup.py -O
RUN chmod +x ./awslogs-agent-setup.py



EXPOSE 8081
CMD ["/usr/bin/supervisord"]
